import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Stdy - Auth Page",
  description: "Generated by STDY",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function AuthLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="w-screen h-screen xl:grid grid-cols-2">
      <img
        src="static/images/auth_background.jpg"
        alt="Auth Background"
        className="h-full object-cover hidden xl:block"
      />
      <div className="h-full flex justify-center items-center">
        {children}
      </div>
    </div>
  );
}
