import Providers from "@/components/Providers";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "STDY - Studying with ease",
  description: "Generated by Stdy",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function SiteLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <Providers>
      <div className="h-screen w-screen flex bg-secondary">
        <Sidebar />
        {children}
      </div>
    </Providers>
  );
}
