import Sidebar from "@/components/Sidebar/Sidebar";
import { UserContextProvider } from "@/contexts/user.context";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StdyHub",
  description: "Generated by STDYHUB",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function SiteLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <UserContextProvider>
      <div className="h-screen w-screen flex">
        <Sidebar />
        {children}
      </div>
    </UserContextProvider>
  );
}
