import { Metadata } from "next";

export const metadata: Metadata = {
  title: "StudyHub",
  description: "Generated by STUDYHUB",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function SiteLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
      {children}
    </div>
  );
}
